import CustomNavbar from '@/components/navbar'
import ReduxProvider from '@/provider/reduxProvider'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <CustomNavbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
